export const GROUP_COLORS = ['#0f4c81','#f18f01','#2a9d8f','#c73e1d','#6c5ce7','#118ab2','#5f8f29','#b56576','#3d5a80','#8d99ae','#bc6c25','#2b9348','#9b5de5','#577590','#e76f51'];
export const GAP_FILL = 50;

export function createState() {
  return {
    datasetId: null, datasetRecord: null, geojson: null,
    analysis: null, map: null, mapBounds: null,
    groups: new Map(), features: [], minute: -1, selectedFeatureId: null,
    mode: 'group', colorMode: 'group', geomMode: 'detail', playTimer: null,
    speed: 1, theme: 'light', hashSyncBlocked: false, pendingHashState: null,
    incidences: { points: [], layer: null, visible: true, clustered: true, fileName: null },
    fused: { built: false, groupLayers: new Map() },
    resolved: { done: false, features: [], previewLayer: null },
    compareMode: 'both',
    csvPaint: { loaded: false, rows: new Map(), columns: [], activeColumn: null, fileName: null, palette: 'heat', manualMin: null, manualMax: null },
  };
}

export function createEls() {
  return {
    title:            document.getElementById('hdr-title'),
    subtitle:         document.getElementById('hdr-sub'),
    statFeatures:     document.getElementById('s-features'),
    statGroups:       document.getElementById('s-groups'),
    statAffected:     document.getElementById('s-affected'),
    statPeak:         document.getElementById('s-peak'),
    btnTheme:         document.getElementById('btn-theme'),
    btnExportCsvAll:  document.getElementById('btn-export-csv-all'),
    btnExportCsvVisible: document.getElementById('btn-export-csv-visible'),
    btnExportFused:   document.getElementById('btn-export-fused'),
    btnResolveOverlaps: document.getElementById('btn-resolve-overlaps'),
    btnExportResolved:  document.getElementById('btn-export-resolved'),
    comparePanel:     document.getElementById('compare-panel'),
    btnCmpBefore:     document.getElementById('btn-cmp-before'),
    btnCmpBoth:       document.getElementById('btn-cmp-both'),
    btnCmpAfter:      document.getElementById('btn-cmp-after'),
    btnFit:           document.getElementById('btn-fit'),
    btnPrint:         document.getElementById('btn-print'),
    btnBack:          document.getElementById('btn-back'),
    sidebar:          document.getElementById('sidebar'),
    btnSidebar:       document.getElementById('btn-sidebar'),
    btnRail:          document.getElementById('btn-rail'),
    btnRailClose:     document.getElementById('btn-rail-close'),
    groupSearch:      document.getElementById('group-search'),
    btnAll:           document.getElementById('btn-all'),
    btnNone:          document.getElementById('btn-none'),
    btnInvert:        document.getElementById('btn-invert'),
    btnAffectedOnly:  document.getElementById('btn-affected-only'),
    btnModeGroup:     document.getElementById('btn-mode-group'),
    btnModeOutage:    document.getElementById('btn-mode-outage'),
    btnColorGroup:    document.getElementById('btn-color-group'),
    btnColorOutage:   document.getElementById('btn-color-outage'),
    btnColorVariable: document.getElementById('btn-color-variable'),
    colorModeHelp:    document.getElementById('color-mode-help'),
    btnGeomToggle:    document.getElementById('btn-geom-toggle'),
    groupsTitle:      document.getElementById('groups-title'),
    groupsVisible:    document.getElementById('groups-visible'),
    groupsList:       document.getElementById('groups-list'),
    btnIncLoad:       document.getElementById('btn-inc-load'),
    incFileInput:     document.getElementById('inc-file-input'),
    btnIncToggle:     document.getElementById('btn-inc-toggle'),
    btnIncCluster:    document.getElementById('btn-inc-cluster'),
    btnIncClear:      document.getElementById('btn-inc-clear'),
    incMeta:          document.getElementById('inc-meta'),
    timeline:         document.getElementById('timeline'),
    timelineTime:     document.getElementById('timeline-time'),
    timelineBadge:    document.getElementById('timeline-badge'),
    timelinePeaks:    document.getElementById('timeline-peaks'),
    timelineScale:    document.getElementById('timeline-scale'),
    timelineSlider:   document.getElementById('timeline-slider'),
    timelineTrack:    document.getElementById('timeline-track'),
    timelineContext:  document.getElementById('timeline-context'),
    btnTlToggle:      document.getElementById('btn-tl-toggle'),
    btnPlay:          document.getElementById('btn-play'),
    btnSpd1:          document.getElementById('btn-spd-1'),
    btnSpd4:          document.getElementById('btn-spd-4'),
    btnSpd8:          document.getElementById('btn-spd-8'),
    btnTimeClear:     document.getElementById('btn-time-clear'),
    rankTitle:        document.getElementById('rank-title'),
    rankSub:          document.getElementById('rank-sub'),
    rankList:         document.getElementById('rank-list'),
    insights:         document.getElementById('insights'),
    insightsCaption:  document.getElementById('insights-caption'),
    insightsSummary:  document.getElementById('insights-summary'),
    insightsCards:    document.getElementById('insights-cards'),
    info:             document.getElementById('info'),
    infoTitle:        document.getElementById('info-title'),
    infoContent:      document.getElementById('info-content'),
    btnInfoClose:     document.getElementById('btn-info-close'),
    statusPill:       document.getElementById('status-pill'),
    btnCsvLoad:       document.getElementById('btn-csv-load'),
    csvFileInput:     document.getElementById('csv-file-input'),
    btnCsvClear:      document.getElementById('btn-csv-clear'),
    csvMeta:          document.getElementById('csv-meta'),
    csvColumns:       document.getElementById('csv-columns'),
    csvOptions:       document.getElementById('csv-options'),
    csvPanel:         document.getElementById('csv-panel'),
    csvPanelTitle:    document.getElementById('csv-panel-title'),
    csvPanelSub:      document.getElementById('csv-panel-sub'),
    csvLegend:        document.getElementById('csv-legend'),
    csvRank:          document.getElementById('csv-rank'),
  };
}
